"""
tests/test_roe_signing.py — RoE HMAC signing + engagement binding (fail-closed).

These tests run in STRICT mode: each fixture deletes the OPENELIA_ALLOW_UNSIGNED_ROE
bypass that conftest's autouse fixture sets, so ScopeValidator exercises the real
verify_roe() path. A deterministic ROE_SIGNING_KEY is injected via env (SecretStore
falls back to os.getenv) so sign and verify share a key.
"""
import json

import pytest

import roe_signing
import secret_store
from security_manager import ScopeValidator

_ROE_KEY = "test-roe-signing-key-deterministic-32bytes"


@pytest.fixture
def strict(monkeypatch):
    """Strict mode with a known signing key; drop the dev bypass."""
    monkeypatch.delenv("OPENELIA_ALLOW_UNSIGNED_ROE", raising=False)
    monkeypatch.setenv("ROE_SIGNING_KEY", _ROE_KEY)
    ScopeValidator._resolution_cache.clear()
    yield
    ScopeValidator._resolution_cache.clear()


def _roe_body():
    return {
        "authorized_subnets": ["10.0.0.0/24"],
        "blacklisted_ips": [],
        "prohibited_tools": [],
        "quiet_hours": {"enabled": False},
    }


class TestSignVerifyRoundTrip:
    def test_signed_roe_verifies(self, strict):
        signed = roe_signing.sign_roe(_roe_body(), engagement_id="ENG-TEST-1")
        ok, reason = roe_signing.verify_roe(signed)
        assert ok, reason
        assert signed["engagement_id"] == "ENG-TEST-1"
        assert "expires_at" in signed and "issued_at" in signed

    def test_engagement_id_autogenerated_when_absent(self, strict):
        signed = roe_signing.sign_roe(_roe_body())
        assert signed["engagement_id"].startswith("ENG-")


class TestFailClosed:
    def test_unsigned_is_rejected(self, strict):
        ok, reason = roe_signing.verify_roe(_roe_body())
        assert not ok and "unsigned" in reason

    def test_tampered_subnet_is_rejected(self, strict):
        signed = roe_signing.sign_roe(_roe_body(), engagement_id="ENG-TEST-2")
        signed["authorized_subnets"] = ["0.0.0.0/0"]  # widen scope post-signing
        ok, reason = roe_signing.verify_roe(signed)
        assert not ok and "mismatch" in reason

    def test_expired_is_rejected(self, strict):
        signed = roe_signing.sign_roe(_roe_body(), engagement_id="ENG-TEST-3", ttl_days=-1)
        ok, reason = roe_signing.verify_roe(signed)
        assert not ok and "expired" in reason

    def test_missing_key_fails_closed(self, monkeypatch):
        """No signing key available → verify cannot run and returns False."""
        monkeypatch.delenv("OPENELIA_ALLOW_UNSIGNED_ROE", raising=False)
        monkeypatch.delenv("ROE_SIGNING_KEY", raising=False)
        monkeypatch.setattr(
            secret_store.SecretStore, "get_secret", staticmethod(lambda k: None)
        )
        doc = {**_roe_body(), "engagement_id": "E", "expires_at": "2999-01-01T00:00:00+00:00",
               "signature": "deadbeef"}
        ok, reason = roe_signing.verify_roe(doc)
        assert not ok and "ROE_SIGNING_KEY is not set" in reason


class TestScopeValidatorStrict:
    def test_signed_roe_loads_and_allows(self, strict, tmp_path, monkeypatch):
        signed = roe_signing.sign_roe(_roe_body(), engagement_id="ENG-SV-1")
        p = tmp_path / "roe.json"
        p.write_text(json.dumps(signed))
        monkeypatch.setenv("OPENELIA_ROE_PATH", str(p))

        sv = ScopeValidator(roe_path=str(p))
        assert sv.roe_loaded is True
        assert sv.is_allowed("10.0.0.5") is True

    def test_unsigned_roe_blocks_all(self, strict, tmp_path, monkeypatch):
        p = tmp_path / "roe.json"
        p.write_text(json.dumps(_roe_body()))  # unsigned
        monkeypatch.setenv("OPENELIA_ROE_PATH", str(p))

        sv = ScopeValidator(roe_path=str(p))
        assert sv.roe_loaded is False
        assert sv.is_allowed("10.0.0.5") is False

    def test_tampered_roe_blocks_all(self, strict, tmp_path, monkeypatch):
        signed = roe_signing.sign_roe(_roe_body(), engagement_id="ENG-SV-2")
        signed["authorized_subnets"] = ["0.0.0.0/0"]
        p = tmp_path / "roe.json"
        p.write_text(json.dumps(signed))
        monkeypatch.setenv("OPENELIA_ROE_PATH", str(p))

        sv = ScopeValidator(roe_path=str(p))
        assert sv.roe_loaded is False
        assert sv.is_allowed("8.8.8.8") is False
